### ISSUE TITLE
Issue with Extracting Options Using manpage_parser.py

### ISSUE THREAD

**Issue by iskindar** [NASP-THU/ProphetFuzz#1]
Hello,

Thank you for your open-source project! I'm currently using the Docker container you provided and ran the following commands:

```bash
docker run -it 4ugustus/prophetfuzz_base bash
cd ~/ProphetFuzz
mkdir manpage_parser/output
python3 ./manpage_parser/parser.py --file ./manpage_parser/input/bison.1
```

However, I encountered an issue where the `manpage_bison.json` file did not successfully extract the options. Here is the output I received:

```json
root@1ab3f4130f7c:/ProphetFuzz# cat manpage_parser/output/manpage_bison.json 
{"description": "", "options": {}, "synopsis": ""}
```

I also tried other program (e.g., tiffcp, exiv2, mutool), but received the same result.

Could you please provide some assistance on how to resolve this issue?

Thank you!

**Comment by iskindar** [comment]
Sorry, after reviewing the parser.py, I found that this part of the code needs to be run in an environment with the `man` command. I was able to successfully run the script on the host machine. As the issue is resolved, I am closing this issue.

**Comment by waugustus** [comment]
Thanks for the update! Great to hear you’ve resolved the issue.
