### ISSUE TITLE
Error when compiling GraphicsMagick

### ISSUE THREAD

**Issue by YukZhao** [NASP-THU/ProphetFuzz#2]
Hello,
Thanks for your open-source project!
I'm interested in this. But when I tried to use the Docker container you provided and test GraphicsMagick, it failed.
Specifically, when I used the compile command you provided in the Dockerfile for this project, an error occurred.
The command is :
```
compile_and_fuzz "$program" "$build_flag"
```
And the error information is :
```
...
ld.lld: error: undefined symbol: omp_get_num_threads
>>> referenced by segment.c:652 (magick/segment.c:652)
>>>               lto.tmp:(.omp_outlined..2774)

ld.lld: error: undefined symbol: omp_set_nested
>>> referenced by command.c:2003 (magick/command.c:2003)
>>>               lto.tmp:(BenchmarkImageCommand)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm not sure if this is because of my environment, but when I tried bison, everything worked fine.

**Comment by waugustus** [comment]
Hi, I’ve actually encountered this issue before. Due to some unexpected reasons, the `libomp5` library in the system can cause the `gm` compilation to fail. You might need to uninstall `libomp5` and then recompile.

**Comment by YukZhao** [comment]
> Hi, I’ve actually encountered this issue before. Due to some unexpected reasons, the `libomp5` library in the system can cause the `gm` compilation to fail. You might need to uninstall `libomp5` and then recompile.

Thanks！I reinstalled `libomp5` and everything worked fine. I will close this issue.

**Comment by waugustus** [comment]
Glad to hear your issue has been resolved! If you find this project helpful, a star would be greatly appreciated. 😄

**Comment by waugustus** [comment]
By the way, based on our experience, compiling `gm` with `libomp5` might succeed, but the resulting binary could potentially fail to run. You can give it a try, but if that's the case, you might need to recompile it without `libomp5` installed.
